### ISSUE TITLE
/port_stats Crashing with Invalid Bounds

### ISSUE THREAD

**Issue by craig-riecke** [frenetic-lang/frenetic#418]
I crashed Frenetic entering:

GET /port_stats/1234567890/12

Stack trace below.  It seems it's having a problem parsing the stats response.  

```
("unhandled exception"
  ((lib/monitor.ml.Error_
    ((exn
      (Invalid_argument
       "invalid bounds in Cstruct.BE.get_uint16 [4,0](4) off=0 len=2"))
     (backtrace
      ("Raised at file \"pervasives.ml\", line 31, characters 25-45"
       "Called from file \"lib/Frenetic_OpenFlow0x01.ml\", line 2264, characters 17-48"
       "Called from file \"lib/Frenetic_OpenFlow0x01.ml\", line 2309, characters 34-55"
       "Called from file \"lib/Frenetic_OpenFlow0x01.ml\", line 2884, characters 37-57"
       "Called from file \"async/Frenetic_OpenFlow0x01_Controller.ml\", line 32, characters 28-57"
       "Called from file \"lib/raw_deferred.ml\", line 55, characters 65-68"
       "Called from file \"lib/job_queue.ml\", line 164, characters 6-47" ""))
     (monitor
      (((name Tcp.collect_errors) (here ()) (id 416) (has_seen_error true)
        (is_detached true) (kill_index 0))))))
   (Pid 7376))))
```

**Comment by arjunguha** [comment]
i was going to post a snarky message saying "working as intended". but, this is a surprising error in the parser.

**Comment by jnfoster** [comment]
We got to the bottom of this: the body of a port stats reply is an *array* and we were simply blindly attempting to parse a single value. Some switches, including OpenVSwitch until recently, would simply return a 0-length array instead of the proper error message. 

The solution is to follow the pattern in individual stats replies and parse the array of values into a list.

@craig-riecke is on it :-)
