### ISSUE TITLE
Frenetic VM link is not Working

### ISSUE THREAD

**Issue by madiha005** [frenetic-lang/frenetic#629]
Hello everyone,
I am trying to get the frenetic user-vm file that has all the necessary prerequisites for starting with frenetic programming but the link provided on programmer guide and Wiki is not working.

http://download.frenetic-lang.org/uservm/frenetic-uservm-current

Can any one help me in knowing which link to use or how to download frenetic ?

**Comment by smolkaj** [comment]
AFAIK there is no VM available at the moment, unfortunately.
You can try building frenetic from source instead, following the instructions from the README.
This is a bit tricky at the moment because there is an issue with a library we depend on, and we're waiting on a fix (see #628, ocaml-community/sedlex#72). Here is a temporary workaround:
1. Check out the branch [fixes](https://github.com/frenetic-lang/frenetic/tree/fixes).
    ```
    git clone -b fixes https://github.com/frenetic-lang/frenetic.git
    ```
2. Follow steps 1-3 of the installation instructions in the README on that branch.
3. Build the newest version of sedlex from source (since it hasn't been released yet):
    ```
    git clone -b release https://github.com/ocaml-community/sedlex.git
    opam pin add -y sedlex sedlex
    ```
4. Build frenetic and its dependencies:
    ```
    opam pin add -y frenetic <path to frenetic root>
    ```

**Comment by madiha005** [comment]
@smolkaj  Thankyou for the reply . Really appreciated. I will try this way.

**Comment by smolkaj** [comment]
The fixes are now merged in, so it should be straightforward to build the master branch of frenetic from source following the instruction in the README.
